@startuml

actor User as user
actor HotelEmployee as employee
actor Administrator as admin

rectangle "Hotel Reservation System" {

  user --> (View Room Availability)
  user --> (Make Reservation)
  user --> (Login)

  employee --> (Enter Room Availability)
  employee --> (Login)

  admin --> (View Reservation Statistics)
  admin --> (Login)

  (Make Reservation) --> (Login)
  (Login) --> (Register as Member)

  (Make Reservation) --> (Apply Promotion)

  (Apply Promotion) --> (View Promotion)

}

@enduml
