@startuml 宿泊予約
left to right direction
actor 利用者 
rectangle ホテル宿泊予約{
    usecase ログインする
    usecase キャンペーン
    usecase (<u>予約する</u>\nキャンペーン期間中ならキャンペーン価格) as input
}
input.> ログインする:<<include>>
 (キャンペーン)   .>input : <<extend>>
利用者-->input
@enduml